[python3] Wrap .values() call into list()
*** Starting 1 switches
s1 Starting P4 switch s1.
simple_switch -i 1@s1-eth1 -i 2@s1-eth2 -i 3@s1-eth3 -i 4@s1-eth4 --pcap=/home/p4/sdn-nat64/test/basic/pcap --thrift-port 9090 --nanolog ipc:///tmp/bm-1-log.ipc --device-id 1 ../../p4src/main.json --log-console >/home/p4/sdn-nat64/test/basic/log/s1.log
P4 switch s1 has been started.

Traceback (most recent call last):
  File "/usr/local/bin/p4run", line 9, in <module>
    load_entry_point('p4utils==0.2', 'console_scripts', 'p4run')()
  File "/usr/local/lib/python3.5/dist-packages/p4utils/p4run.py", line 432, in main
    app.run_app()
  File "/usr/local/lib/python3.5/dist-packages/p4utils/p4run.py", line 231, in run_app
    self.program_hosts()
  File "/usr/local/lib/python3.5/dist-packages/p4utils/p4run.py", line 310, in program_hosts
    h_iface = h.intfs.values()[0]
TypeError: 'dict_values' object does not support indexing
=================================================== 1 error in 7.14 seconds ===================================================
(venv) p4@ubuntu:~/sdn-nat64/test$

https://stackoverflow.com/questions/17431638/get-typeerror-dict-values-object-does-not-support-indexing-when-using-python